# Form implementation generated from reading ui file 'mainV0.1.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(820, 500))
        MainWindow.setStyleSheet(" background-color: #f0f0f0;\n"
"color:black;\n"
"            ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(810, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(810, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 810, 551))
        self.frame.setMinimumSize(QtCore.QSize(810, 551))
        self.frame.setMaximumSize(QtCore.QSize(810, 551))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame)
        self.groupBox.setGeometry(QtCore.QRect(25, 20, 761, 85))
        self.groupBox.setStyleSheet(" QGroupBox {\n"
"                border: 2px solid #0078D7;\n"
"                border-radius: 8px;\n"
"                margin-top: 10px;\n"
"                background-color: #ffffff;\n"
"                font-size: 12pt;\n"
"                font-weight: bold;\n"
"                color: #0078D7;\n"
"            }\n"
"QGroupBox::title {\n"
"                subcontrol-origin: margin;\n"
"                subcontrol-position: top left;\n"
"                padding: 0 5px;\n"
"            }")
        self.groupBox.setObjectName("groupBox")
        self.iccid_dec_btn = QtWidgets.QPushButton(parent=self.groupBox)
        self.iccid_dec_btn.setGeometry(QtCore.QRect(660, 40, 91, 31))
        self.iccid_dec_btn.setStyleSheet(" QPushButton {\n"
"                background-color: #0078D7;\n"
"                color: white;\n"
"                border-radius: 6px;\n"
"                padding: 5px 10px;\n"
"                font-size: 10pt;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #005a9e;\n"
"            }\n"
"            ")
        self.iccid_dec_btn.setObjectName("iccid_dec_btn")
        self.iccid_input = QtWidgets.QLineEdit(parent=self.groupBox)
        self.iccid_input.setGeometry(QtCore.QRect(10, 40, 260, 30))
        self.iccid_input.setStyleSheet(" QLineEdit {\n"
"                border: 1px solid #d3d3d3;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                background-color: #ffffff;\n"
"                font-family: \"Segoe UI\";\n"
"                font-size: 10pt;\n"
"            }")
        self.iccid_input.setMaxLength(20)
        self.iccid_input.setObjectName("iccid_input")
        self.iccid_output = QtWidgets.QLineEdit(parent=self.groupBox)
        self.iccid_output.setGeometry(QtCore.QRect(280, 40, 260, 30))
        self.iccid_output.setStyleSheet(" QLineEdit {\n"
"                border: 1px solid #d3d3d3;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                background-color: #ffffff;\n"
"                font-family: \"Segoe UI\";\n"
"                font-size: 10pt;\n"
"            }")
        self.iccid_output.setReadOnly(True)
        self.iccid_output.setObjectName("iccid_output")
        self.iccid_enc_btn = QtWidgets.QPushButton(parent=self.groupBox)
        self.iccid_enc_btn.setGeometry(QtCore.QRect(560, 40, 91, 31))
        self.iccid_enc_btn.setStyleSheet(" QPushButton {\n"
"                background-color: #0078D7;\n"
"                color: white;\n"
"                border-radius: 6px;\n"
"                padding: 5px 10px;\n"
"                font-size: 10pt;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #005a9e;\n"
"            }\n"
"            ")
        self.iccid_enc_btn.setObjectName("iccid_enc_btn")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(290, 20, 101, 16))
        self.label_10.setStyleSheet("QLabel {\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"background:transparent;\n"
"        }")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_9.setStyleSheet("QLabel {\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"background:transparent;\n"
"        }")
        self.label_9.setObjectName("label_9")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(25, 210, 761, 221))
        self.groupBox_2.setStyleSheet(" QGroupBox {\n"
"                border: 2px solid #0078D7;\n"
"                border-radius: 8px;\n"
"                margin-top: 10px;\n"
"                background-color: #ffffff;\n"
"                font-size: 12pt;\n"
"                font-weight: bold;\n"
"                color: #0078D7;\n"
"            }\n"
"QGroupBox::title {\n"
"                subcontrol-origin: margin;\n"
"                subcontrol-position: top left;\n"
"                padding: 0 5px;\n"
"            }")
        self.groupBox_2.setObjectName("groupBox_2")
        self.enc_keys_conv_btn = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.enc_keys_conv_btn.setGeometry(QtCore.QRect(660, 170, 91, 31))
        self.enc_keys_conv_btn.setStyleSheet(" QPushButton {\n"
"                background-color: #0078D7;\n"
"                color: white;\n"
"                border-radius: 6px;\n"
"                padding: 5px 10px;\n"
"                font-size: 10pt;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #005a9e;\n"
"            }\n"
"            ")
        self.enc_keys_conv_btn.setObjectName("enc_keys_conv_btn")
        self.ki = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.ki.setGeometry(QtCore.QRect(10, 50, 281, 30))
        self.ki.setStyleSheet(" QLineEdit {\n"
"                border: 1px solid #d3d3d3;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                background-color: #ffffff;\n"
"                font-family: \"Segoe UI\";\n"
"                font-size: 10pt;\n"
"            }")
        self.ki.setMaxLength(32)
        self.ki.setObjectName("ki")
        self.op = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.op.setGeometry(QtCore.QRect(300, 50, 281, 30))
        self.op.setStyleSheet(" QLineEdit {\n"
"                border: 1px solid #d3d3d3;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                background-color: #ffffff;\n"
"                font-family: \"Segoe UI\";\n"
"                font-size: 10pt;\n"
"            }")
        self.op.setMaxLength(32)
        self.op.setObjectName("op")
        self.k4 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.k4.setGeometry(QtCore.QRect(10, 110, 571, 30))
        self.k4.setStyleSheet(" QLineEdit {\n"
"                border: 1px solid #d3d3d3;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                background-color: #ffffff;\n"
"                font-family: \"Segoe UI\";\n"
"                font-size: 10pt;\n"
"            }")
        self.k4.setMaxLength(64)
        self.k4.setObjectName("k4")
        self.opc = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.opc.setGeometry(QtCore.QRect(10, 170, 281, 30))
        self.opc.setStyleSheet(" QLineEdit {\n"
"                border: 1px solid #d3d3d3;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                background-color: #ffffff;\n"
"                font-family: \"Segoe UI\";\n"
"                font-size: 10pt;\n"
"            }")
        self.opc.setReadOnly(True)
        self.opc.setObjectName("opc")
        self.eki = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.eki.setGeometry(QtCore.QRect(300, 170, 281, 30))
        self.eki.setStyleSheet(" QLineEdit {\n"
"                border: 1px solid #d3d3d3;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                background-color: #ffffff;\n"
"                font-family: \"Segoe UI\";\n"
"                font-size: 10pt;\n"
"            }")
        self.eki.setReadOnly(True)
        self.eki.setObjectName("eki")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 49, 16))
        self.label_2.setStyleSheet("QLabel {\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"background:transparent;\n"
"        }")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(300, 150, 49, 16))
        self.label_3.setStyleSheet("QLabel {\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"background:transparent;\n"
"        }")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 49, 16))
        self.label_4.setStyleSheet("QLabel {\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"background:transparent;\n"
"        }")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 49, 16))
        self.label_5.setStyleSheet("QLabel {\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"background:transparent;\n"
"        }")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(300, 30, 49, 16))
        self.label_6.setStyleSheet("QLabel {\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"background:transparent;\n"
"        }")
        self.label_6.setObjectName("label_6")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(25, 120, 761, 85))
        self.groupBox_3.setStyleSheet(" QGroupBox {\n"
"                border: 2px solid #0078D7;\n"
"                border-radius: 8px;\n"
"                margin-top: 10px;\n"
"                background-color: #ffffff;\n"
"                font-size: 12pt;\n"
"                font-weight: bold;\n"
"                color: #0078D7;\n"
"            }\n"
"QGroupBox::title {\n"
"                subcontrol-origin: margin;\n"
"                subcontrol-position: top left;\n"
"                padding: 0 5px;\n"
"            }")
        self.groupBox_3.setObjectName("groupBox_3")
        self.imsi_enc_btn = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.imsi_enc_btn.setGeometry(QtCore.QRect(560, 40, 91, 31))
        self.imsi_enc_btn.setStyleSheet(" QPushButton {\n"
"                background-color: #0078D7;\n"
"                color: white;\n"
"                border-radius: 6px;\n"
"                padding: 5px 10px;\n"
"                font-size: 10pt;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #005a9e;\n"
"            }\n"
"            ")
        self.imsi_enc_btn.setObjectName("imsi_enc_btn")
        self.imsi_input = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.imsi_input.setGeometry(QtCore.QRect(10, 40, 261, 30))
        self.imsi_input.setStyleSheet(" QLineEdit {\n"
"                border: 1px solid #d3d3d3;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                background-color: #ffffff;\n"
"                font-family: \"Segoe UI\";\n"
"                font-size: 10pt;\n"
"            }")
        self.imsi_input.setMaxLength(18)
        self.imsi_input.setObjectName("imsi_input")
        self.imsi_output = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.imsi_output.setGeometry(QtCore.QRect(280, 40, 261, 30))
        self.imsi_output.setStyleSheet(" QLineEdit {\n"
"                border: 1px solid #d3d3d3;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                background-color: #ffffff;\n"
"                font-family: \"Segoe UI\";\n"
"                font-size: 10pt;\n"
"            }")
        self.imsi_output.setReadOnly(True)
        self.imsi_output.setObjectName("imsi_output")
        self.imsi_dec_btn = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.imsi_dec_btn.setGeometry(QtCore.QRect(660, 40, 91, 31))
        self.imsi_dec_btn.setStyleSheet(" QPushButton {\n"
"                background-color: #0078D7;\n"
"                color: white;\n"
"                border-radius: 6px;\n"
"                padding: 5px 10px;\n"
"                font-size: 10pt;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #005a9e;\n"
"            }\n"
"            ")
        self.imsi_dec_btn.setObjectName("imsi_dec_btn")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_7.setStyleSheet("QLabel {\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"background:transparent;\n"
"        }")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(290, 20, 101, 16))
        self.label_8.setStyleSheet("QLabel {\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"background:transparent;\n"
"        }")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 22))
        self.menubar.setObjectName("menubar")
        self.menuSetting = QtWidgets.QMenu(parent=self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.k4_length = QtGui.QAction(parent=MainWindow)
        self.k4_length.setCheckable(False)
        self.k4_length.setObjectName("k4_length")
        self.exit = QtGui.QAction(parent=MainWindow)
        self.exit.setObjectName("exit")
        self.menuSetting.addAction(self.k4_length)
        self.menuFile.addAction(self.exit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STCards"))
        self.groupBox.setTitle(_translate("MainWindow", "ICCID"))
        self.iccid_dec_btn.setText(_translate("MainWindow", "Decode"))
        self.iccid_enc_btn.setText(_translate("MainWindow", "Encode"))
        self.label_10.setText(_translate("MainWindow", "Output"))
        self.label_9.setText(_translate("MainWindow", "Input"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Encryption Keys"))
        self.enc_keys_conv_btn.setText(_translate("MainWindow", "Convert"))
        self.label_2.setText(_translate("MainWindow", "OPC"))
        self.label_3.setText(_translate("MainWindow", "EKI"))
        self.label_4.setText(_translate("MainWindow", "K4"))
        self.label_5.setText(_translate("MainWindow", "Ki"))
        self.label_6.setText(_translate("MainWindow", "OP"))
        self.groupBox_3.setTitle(_translate("MainWindow", "IMSI"))
        self.imsi_enc_btn.setText(_translate("MainWindow", "Encode"))
        self.imsi_dec_btn.setText(_translate("MainWindow", "Decode"))
        self.label_7.setText(_translate("MainWindow", "Input"))
        self.label_8.setText(_translate("MainWindow", "Output"))
        self.menuSetting.setTitle(_translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.k4_length.setText(_translate("MainWindow", "K4 Length"))
        self.exit.setText(_translate("MainWindow", "Exit"))
