# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 450)
        MainWindow.setMinimumSize(QtCore.QSize(791, 450))
        MainWindow.setMaximumSize(QtCore.QSize(791, 450))
        MainWindow.setStyleSheet(" QMainWindow {\n"
"                background: linear-gradient(45deg, #00BFFF, #1E90FF);\n"
"            }\n"
"            ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 0, 791, 551))
        self.frame.setMinimumSize(QtCore.QSize(791, 551))
        self.frame.setMaximumSize(QtCore.QSize(791, 551))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame)
        self.groupBox.setGeometry(QtCore.QRect(0, 50, 761, 71))
        self.groupBox.setStyleSheet("  QGroupBox {\n"
"                border: 2px solid #B0B0B0;\n"
"                border-radius: 10px;\n"
"                background-color: #E0E0E0;\n"
"                padding: 10px;\n"
"            }\n"
"            QGroupBox::title {\n"
"                font-size: 18px;\n"
"                font-weight: bold;\n"
"                color: #333333;\n"
"            }")
        self.groupBox.setObjectName("groupBox")
        self.iccid_dec = QtWidgets.QTextEdit(parent=self.groupBox)
        self.iccid_dec.setGeometry(QtCore.QRect(10, 20, 281, 31))
        self.iccid_dec.setStyleSheet("   QTextEdit {\n"
"                background-color: #FFFFFF;\n"
"                border: 1px solid #B0B0B0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"            }")
        self.iccid_dec.setObjectName("iccid_dec")
        self.iccid_enc = QtWidgets.QTextEdit(parent=self.groupBox)
        self.iccid_enc.setGeometry(QtCore.QRect(300, 20, 281, 31))
        self.iccid_enc.setStyleSheet("QTextEdit {\n"
"                background-color: #FFFFFF;\n"
"                border: 1px solid #B0B0B0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"            }")
        self.iccid_enc.setObjectName("iccid_enc")
        self.iccid_conv_btn = QtWidgets.QPushButton(parent=self.groupBox)
        self.iccid_conv_btn.setGeometry(QtCore.QRect(620, 20, 91, 31))
        self.iccid_conv_btn.setStyleSheet("  QPushButton {\n"
"                background-color: #A9A9A9;\n"
"                color: Black;\n"
"                font-weight: bold;\n"
"                border-radius: 10px;\n"
"                padding: 8px;\n"
"                font-size: 14px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #808080;\n"
"            }")
        self.iccid_conv_btn.setObjectName("iccid_conv_btn")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 220, 761, 181))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"                border: 2px solid #B0B0B0;\n"
"                border-radius: 10px;\n"
"                background-color: #E0E0E0;\n"
"                padding: 10px;\n"
"            }\n"
"            QGroupBox::title {\n"
"                font-size: 18px;\n"
"                font-weight: bold;\n"
"                color: #333333;\n"
"            }")
        self.groupBox_2.setObjectName("groupBox_2")
        self.ki = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.ki.setGeometry(QtCore.QRect(10, 20, 351, 30))
        self.ki.setStyleSheet(" QTextEdit {\n"
"                background-color: #FFFFFF;\n"
"                border: 1px solid #B0B0B0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"            }")
        self.ki.setObjectName("ki")
        self.opc = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.opc.setGeometry(QtCore.QRect(10, 100, 351, 30))
        self.opc.setStyleSheet(" QTextEdit {\n"
"                background-color: #FFFFFF;\n"
"                border: 1px solid #B0B0B0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"            }")
        self.opc.setReadOnly(True)
        self.opc.setObjectName("opc")
        self.k4 = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.k4.setGeometry(QtCore.QRect(10, 60, 701, 31))
        self.k4.setStyleSheet(" QTextEdit {\n"
"                background-color: #FFFFFF;\n"
"                border: 1px solid #B0B0B0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"            }")
        self.k4.setObjectName("k4")
        self.eki = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.eki.setGeometry(QtCore.QRect(369, 100, 341, 30))
        self.eki.setStyleSheet(" QTextEdit {\n"
"                background-color: #FFFFFF;\n"
"                border: 1px solid #B0B0B0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"            }")
        self.eki.setReadOnly(True)
        self.eki.setObjectName("eki")
        self.op = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.op.setGeometry(QtCore.QRect(369, 20, 341, 30))
        self.op.setStyleSheet(" QTextEdit {\n"
"                background-color: #FFFFFF;\n"
"                border: 1px solid #B0B0B0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"            }")
        self.op.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhMultiLine)
        self.op.setObjectName("op")
        self.imsi_conv_btn_2 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.imsi_conv_btn_2.setGeometry(QtCore.QRect(620, 140, 91, 31))
        self.imsi_conv_btn_2.setStyleSheet("  QPushButton {\n"
"                background-color: #A9A9A9;\n"
"                color: Black;\n"
"                font-weight: bold;\n"
"                border-radius: 10px;\n"
"                padding: 8px;\n"
"                font-size: 14px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #808080;\n"
"            }")
        self.imsi_conv_btn_2.setObjectName("imsi_conv_btn_2")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 130, 761, 71))
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"                border: 2px solid #B0B0B0;\n"
"                border-radius: 10px;\n"
"                background-color: #E0E0E0;\n"
"                padding: 10px;\n"
"            }\n"
"            QGroupBox::title {\n"
"                font-size: 18px;\n"
"                font-weight: bold;\n"
"                color: #333333;\n"
"            }")
        self.groupBox_3.setObjectName("groupBox_3")
        self.imsi_dec = QtWidgets.QTextEdit(parent=self.groupBox_3)
        self.imsi_dec.setGeometry(QtCore.QRect(10, 20, 281, 31))
        self.imsi_dec.setStyleSheet("  QTextEdit {\n"
"                background-color: #FFFFFF;\n"
"                border: 1px solid #B0B0B0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"            }")
        self.imsi_dec.setObjectName("imsi_dec")
        self.imsi_enc = QtWidgets.QTextEdit(parent=self.groupBox_3)
        self.imsi_enc.setGeometry(QtCore.QRect(300, 20, 280, 30))
        self.imsi_enc.setStyleSheet("QTextEdit {\n"
"                background-color: #FFFFFF;\n"
"                border: 1px solid #B0B0B0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                font-size: 14px;\n"
"            }")
        self.imsi_enc.setObjectName("imsi_enc")
        self.imsi_conv_btn = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.imsi_conv_btn.setGeometry(QtCore.QRect(620, 20, 91, 31))
        self.imsi_conv_btn.setStyleSheet("  QPushButton {\n"
"                background-color: #A9A9A9;\n"
"                color: Black;\n"
"                font-weight: bold;\n"
"                border-radius: 10px;\n"
"                padding: 8px;\n"
"                font-size: 14px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #808080;\n"
"            }")
        self.imsi_conv_btn.setObjectName("imsi_conv_btn")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(290, 10, 151, 31))
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setStyleSheet("  QLabel {\n"
"                background-color: #F5F5F5;\n"
"                border: 1px solid #D3D3D3;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"   font-weight: bold;\n"
"text:center;\n"
"                font-size: 16px;\n"
"            }\n"
"     ")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "ICCID"))
        self.iccid_conv_btn.setText(_translate("MainWindow", "Convert"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Encryption Keys"))
        self.imsi_conv_btn_2.setText(_translate("MainWindow", "Convert"))
        self.groupBox_3.setTitle(_translate("MainWindow", "IMSI"))
        self.imsi_conv_btn.setText(_translate("MainWindow", "Convert"))
        self.label.setText(_translate("MainWindow", "Encoder-Decoder"))
